### ISSUE TITLE
Validate DispatchConsumersAsync from ConnectionFactory

### ISSUE THREAD

**Issue by luizcarlosfaria** [luizcarlosfaria/Oragon.RabbitMQ#16]
When user ignore DispatchConsumersAsync boolean property of ConnectionFactory, consumer never will be called.

-- 
Users do not configure `ConnectionFactory` properly, ignoring `DispatchConsumersAsync` property (by default is false).

The way to make consistence guarantee is requesting the user `ConnectionFactory` to do my validations but by design handle the `ConnectionFactory` is not Oragon.RabbitMQ business. 

`ConnectionFactory` and `Connection` is handled by user code, the Oragon.RabbitMQ job is to use a valid `connection` to create a consumer.

The effect is that consumer never be called.

This approach enables user code to handle connection lifecycle and granularity.

Is user responsible to choose between:
- A shared connection for all consumers (per process)
- A exclusive connection per consumer (per process)
- A mix of shared and exclusive connections choosing by user (per process)

A [pull request](https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1611) was created on [rabbitmq/rabbitmq-dotnet-client](https://github.com/rabbitmq/rabbitmq-dotnet-client), but this PR was closed.

**Comment by lukebakken** [comment]
Hello, please see this PR - https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1615

**Comment by luizcarlosfaria** [comment]
@lukebakken thank you so much!!
